services:
  app:
    image: cesal-scraper
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cesal-scraper
    env_file:
      - .env
    volumes:
      - ./src:/app
      - ./pyproject.toml:/pyproject.toml
