[tool.ruff]
line-length    = 120
target-version = "py312"

    [tool.ruff.lint]
    ignore = [
        "D100",
        "D101",
        "D102",
        'D103',
        "D104",
        "D105",
        "D106",
        "D107",
        "D203",
        "D212",
        "ANN002",
        "ANN003",
        "ANN101",
        "ARG002",
        "PGH003",
        "PT009",
        "COM812",
        "ISC001",
        "RUF012",
        "TRY003",
        "G004",
        "EM101",
        "FBT001",
        "PLR2004",
        "TRY002",
        "EM102",
        "DTZ007",
        "FBT002",
    ]
    select = ["ALL"]
        [tool.ruff.lint.isort]
        section-order = [
            "future",
            "standard-library",
            "third-party",
            "first-party",
            "local-folder",
        ]
        known-first-party = ["notification"]
